[build]
  command = "npm run build"
  publish = ".next"
  
  [build.environment]
    NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = ""
  STRIPE_SECRET_KEY = ""